# Generated by Django 4.2.1 on 2023-06-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_car_model_alter_car_brand'),
        ('cars', '0007_alter_car_photo'),
    ]

    operations = [
    ]
