# Generated by Django 4.2.1 on 2023-06-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_merge_20230605_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=200),
        ),
    ]
