# Generated by Django 4.2.1 on 2023-07-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_rename_cars_counts_carinventory_cars_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
